a<-read.csv("multi_variable.csv")
id_r<-!is.na(a[,2])
id_c<-!is.na(a[1,])
d=a[id_r,id_c]
cid=d[,1]
m=length(cid)
for(i in 1:m)
{
if(d[i,1]<10)
{
cid[i]=paste("WH0",d[i,1],".CEL",sep="")
}
else
{
cid[i]=paste("WH",d[i,1],".CEL",sep="")
}
}
raw_pheno=data.frame(cid,d)
e0<-read.delim("cmb.rma.3.gene.exp",header=T)
pheno_all=raw_pheno[match(colnames(e0)[-(1:2)],raw_pheno$cid),]
pheno1=pheno_all$BMI
pheno2=pheno_all$newRestrained
pheno3=pheno_all$Weight
e=as.matrix(e0[,-(1:2)])
n=length(e[,1])
r=array(dim=c(n,3))
for(i in 1:n)
{
print(i)
r[i,1]=i
r[i,2]=cor.test(e[i,],pheno1,method="spearman")$p.value
}
r[,3]=p.adjust(r[,2],method="BH")
id=which(r[,3]<0.05)
s_e0=r[id,]
s_e1=s_e0[order(s_e0[,3]),]
n_id=s_e1[,1]
s_id=c(n_id[1])
for(i in 2:length(n_id))
{
t_n=length(s_id)
gd=1
for(j in 1:t_n)
{
tt=cor.test(e[n_id[i],],e[s_id[j],],method="spearman")$p.value
if(tt<0.01)
{
gd=0
break
}
}
if(gd==1)
{
s_id=c(s_id,n_id[i])
}
print(t_n)
}
out=data.frame(weight=pheno3,eating=pheno2,bmi=pheno1,t(e[s_id,]))
write.csv(out,file="bmi2exp.csv")

