a<-read.delim("regression_sin.data",header=T)
c=as.matrix(a)
n=length(c[1,])
m=length(c[,1])
c_1=c
c_2=c
for(i in 3:(n-2))
{
d1=c[,i]
d2=which(d1==-1)
d1[d2]=0
c_1[,i]=d1
e1=c[,i]
e2=which(e1>-1)
e1[e2]=0
c_2[,i]=e1
}
tag=array(0,dim=c(n))
excl=array(0,dim=c(n-4))
pval=array(0,dim=c(n-4))
rval=array(0,dim=c(n-4))
x_n=c[,(n-1)]
x_g=c[,n]
for(j in 1:20)
{
min_p=1
min_id=0
max_r=0
for(i in 3:(n-2))
{
if(tag[i]==0)
{
s_n=x_n-1-c_2[,i]
s_g=x_g-c_1[,i]
t=cor.test(c[,2],(s_g/s_n),method="pearson")$p.value
tt=cor(c[,2],(s_g/s_n),method="pearson")
if(t<min_p)
{
min_p=t
min_id=i
max_r=tt
}
}
}
#print(min_p)
#print(min_id)
tag[min_id]=1
x_n=x_n-1-c_2[,min_id]
x_g=x_g-c_1[,min_id]
excl[j]=min_id
pval[j]=min_p
rval[j]=max_r
#print(x_n)
}
excl
pval
rval